// apps/client/src/components/common/GroupAvatar.tsx
import Image from 'next/image'
import { isNullOrUndefined } from '@arpansaha13/utils'
import { UserGroupIcon } from '@heroicons/react/24/solid'

interface GroupAvatarProps {
  src: string | null | undefined
  alt?: string
  /**
   * Width of the avatar in 'rem' units.
   * @default 4
   */
  width?: number
  /**
   * Height of the avatar in 'rem' units.
   * @default 4
   */
  height?: number
}

export default function GroupAvatar(props: Readonly<GroupAvatarProps>) {
  const { src, width = 4, height = 4, alt = '' } = props

  if (isNullOrUndefined(src)) {
    return (
      <div
        className="flex flex-shrink-0 items-center justify-center overflow-hidden rounded-full bg-gray-500"
        style={{ width: `${width}rem`, height: `${height}rem` }}
      >
        <UserGroupIcon className="size-3/4 text-gray-200" />
      </div>
    )
  }

  return (
    <div className="relative" style={{ width: `${width}rem`, height: `${height}rem` }}>
      <Image className="rounded-full" src={src} alt={alt} fill />
    </div>
  )
}

// apps/frontend/src/components/GroupAvatar.vue
<template>
  <div
    class="flex flex-shrink-0 items-center justify-center overflow-hidden rounded-full bg-gray-500"
    :style="{ width: `${size}rem`, height: `${size}rem` }"
  >
    <template v-if="src">
      <img :src="src" :alt="alt" class="size-full rounded-full object-cover">
    </template>
    <template v-else>
      <UserGroupIcon class="size-3/4 text-gray-200" />
    </template>
  </div>
</template>

<script setup lang="ts">
import { UserGroupIcon } from '@heroicons/vue/24/solid'

withDefaults(
  defineProps<{
    src?: string | null
    alt?: string
    size?: number
  }>(),
  {
    src: null,
    alt: '',
    size: 4,
  },
)
</script>
