// apps/frontend/src/components/Avatar.vue
<template>
  <div class="relative overflow-hidden rounded-full" :style="{ width: `${size}rem`, height: `${size}rem` }">
    <img v-if="hasImage" :src="src || ''" :alt="alt" class="size-full rounded-full object-cover" />
    <AvatarSvg
      v-else
      :size="size"
      bg-color="bg-gray-500 dark:bg-gray-500"
      svg-color="text-gray-300 dark:text-gray-300"
    />
  </div>
</template>

<script setup lang="ts">
import AvatarSvg from './AvatarSvg.vue'

const props = defineProps<{
  src?: string | null
  alt?: string
  size: number
}>()

const hasImage = computed(() => Boolean(props.src))
</script>

// apps/client/src/components/common/Avatar.tsx
import Image from 'next/image'
import { classNames, isNullOrUndefined } from '@arpansaha13/utils'

type TwColorShades = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950

interface AvatarProps {
  src: string | null | undefined
  alt?: string

  /** Size of the avatar in 'rem' units. */
  size: number
}

interface AvatarSvgProps {
  size: number
  bgColor: `bg-gray-${TwColorShades} dark:bg-gray-${TwColorShades}`
  svgColor: `text-gray-${TwColorShades} dark:text-gray-${TwColorShades}`
}

export default function Avatar(props: Readonly<AvatarProps>) {
  const { src, size, alt = '' } = props

  if (isNullOrUndefined(src)) {
    return <AvatarSvg size={size} bgColor="bg-gray-500 dark:bg-gray-500" svgColor="text-gray-300 dark:text-gray-500" />
  }

  return (
    <div className="relative" style={{ width: `${size}rem`, height: `${size}rem` }}>
      <Image className="rounded-full" src={src} alt={alt} fill />
    </div>
  )
}

export function AvatarSvg(props: Readonly<AvatarSvgProps>) {
  const { size, bgColor, svgColor } = props

  return (
    <div
      className={classNames('flex-shrink-0 overflow-hidden rounded-full', bgColor)}
      style={{ width: `${size}rem`, height: `${size}rem` }}
    >
      <svg className={classNames('size-full', svgColor)} fill="currentColor" viewBox="0 0 24 24">
        <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
    </div>
  )
}
