// apps/client/components/Chat/index.tsx
import ChatBody from './Body'
import ChatHeader from './Header'
import ChatFooter from './Footer'

export default function Chat() {
  return (
    <div className="flex flex-col h-full">
      <div className="px-4 py-2.5 flex items-center justify-between bg-gray-100 dark:bg-gray-800 shadow-sm shadow-gray-400/30 dark:shadow-none relative z-10">
        <ChatHeader />
      </div>

      <div className="flex-grow flex flex-col justify-end bg-slate-200/50 dark:bg-gray-900 overflow-hidden">
        <ChatBody />
      </div>

      <div className="px-4 py-2.5 w-full flex items-center text-gray-900 dark:text-gray-400 bg-gray-100 dark:bg-gray-800 space-x-1 shadow-[0_-1px_2px_0] shadow-gray-300/20 dark:shadow-none relative z-10">
        <ChatFooter />
      </div>
    </div>
  )
}

// apps/frontend/src/components/chat/index.vue
<template>
  <div class="flex h-full flex-col">
    <div
      v-if="$slots.header"
      class="relative z-10 flex items-center justify-between bg-gray-100 px-4 py-2.5 shadow-sm shadow-gray-400/30 dark:bg-gray-800 dark:shadow-none"
    >
      <slot name="header" />
    </div>

    <div v-if="$slots.body" class="flex grow flex-col justify-end overflow-hidden bg-slate-200/50 dark:bg-gray-900">
      <slot name="body" />
    </div>

    <div
      v-if="$slots.footer"
      class="relative z-10 flex w-full items-center space-x-1 bg-gray-100 px-4 py-2.5 text-gray-900 shadow-[0_-1px_2px_0] shadow-gray-300/20 dark:bg-gray-800 dark:text-gray-400 dark:shadow-none"
    >
      <slot name="footer" />
    </div>
  </div>
</template>
